# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
